# Generated by Django 4.2.7 on 2023-11-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Modelo', models.TextField()),
                ('Tipo', models.TextField()),
                ('Precio', models.FloatField()),
                ('Fecha_Lanzamiento', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
